[features]
seeds = false
skip-lint = false
[programs.devnet]
anchor = "EozGe4eZCQE3gTuJwUT8ufM4e7EAVc4VSnjP2nHax7om"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/sarahgregorio/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
