[features]
seeds = false
skip-lint = false
[programs.devnet]
anchor = "BbqB5v7ukqDquJ1TaDTZfsYtuE51QLJZe76VGdc6xgZC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/sarahgregorio/solana-wallet/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
